fix: make sidekiq instrumentation rake task compatible with TruffleRuby
This commit fixes the following error due to using `fork` for starting
redis:

```
NotImplementedError: fork is not available
```